# Generated by Django 4.2.4 on 2023-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('ch', 'грудь'), ('bi', 'бицепс'), ('ba', 'спина'), ('tr', 'трицепс'), ('le', 'ноги'), ('sh', 'плечи'), ('ca', 'кардио')], max_length=2)),
                ('media', models.ImageField(upload_to='uploads')),
                ('description', models.TextField()),
            ],
        ),
    ]
