# Generated by Django 4.2.4 on 2023-10-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_exercise_options_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.AlterModelOptions(
            name='userexercise',
            options={'verbose_name': 'Упражнение пользователя', 'verbose_name_plural': 'Упражнения пользователей'},
        ),
    ]
